import Foundation

/// Apps der AbfallPlus-Plattform mit den Regionen, die sie abdecken.
/// Generiert aus hacs_waste_collection_schedule (MIT), Stand Oktober 2026.
enum AbfallPlusAppCatalog {
    static let services: [(appID: String, regions: [String])] = [
        ("de.albagroup.app", ["Berlin", "Braunschweig", "Havelland", "Oberhavel", "Ostprignitz-Ruppin", "Tübingen"]),
        ("de.k4systems.abfallinfocw", ["Kreis Calw"]),
        ("de.k4systems.abfallinfoapp", ["Kreis Euskirchen", "Bad Münstereifel", "Dahlem", "Hellenthal", "Kall", "Mechernich", "Schleiden", "Weilerswist", "Zülpich"]),
        ("de.k4systems.abfallappes", ["Landkreis Esslingen"]),
        ("de.k4systems.egst", ["Kreis Steinfurt"]),
        ("de.idcontor.abfallwbd", ["Duisburg"]),
        ("de.ucom.abfallavr", ["Rhein-Neckar-Kreis"]),
        ("de.k4systems.abfallapprv", ["Kreis Ravensburg"]),
        ("de.k4systems.avlserviceplus", ["Kreis Ludwigsburg"]),
        ("de.k4systems.muellalarm", ["Schönmackers"]),
        ("de.k4systems.abfallapploe", ["Kreis Lörrach"]),
        ("de.k4systems.abfallapp", ["Kreis Augsburg"]),
        ("de.k4systems.abfallappvorue", ["Kreis Vorpommern-Rügen"]),
        ("de.k4systems.abfallappfds", ["Kreis Freudenstadt"]),
        ("de.k4systems.abfallscout", ["Kreis Bad Kissingen"]),
        ("de.k4systems.avea", ["Leverkusen"]),
        ("de.k4systems.neustadtaisch", ["Kreis Neustadt/Aisch-Bad Windsheim"]),
        ("de.k4systems.abfalllkswp", ["Kreis Südwestpfalz"]),
        ("de.k4systems.awbemsland", ["Kreis Emsland"]),
        ("de.k4systems.abfallappclp", ["Kreis Cloppenburg"]),
        ("de.k4systems.abfallappnf", ["Kreis Nordfriesland"]),
        ("de.k4systems.abfallappog", ["Ortenaukreis"]),
        ("de.k4systems.abfallappmol", ["Kreis Märkisch-Oderland"]),
        ("de.k4systems.kufiapp", ["Landkreis Wunsiedel im Fichtelgebirge"]),
        ("de.k4systems.abfalllkbz", ["Kreis Bautzen"]),
        ("de.k4systems.abfallappbb", ["Landkreis Böblingen"]),
        ("de.k4systems.abfallappla", ["Landshut"]),
        ("de.k4systems.abfallappwug", ["Kreis Weißenburg-Gunzenhausen"]),
        ("de.k4systems.abfallappik", ["Ilm-Kreis"]),
        ("de.k4systems.leipziglk", ["Landkreis Leipzig"]),
        ("de.k4systems.abfallappbk", ["Bad Kissingen"]),
        ("de.cmcitymedia.hokwaste", ["Hohenlohekreis"]),
        ("de.abfallwecker", ["Tuttlingen", "Prignitz", "Osterode am Harz", "Nordsachsen"]),
        ("de.k4systems.abfallappka", ["Kreis Karlsruhe"]),
        ("de.k4systems.lkgoettingen", ["Kreis Göttingen"]),
        ("de.k4systems.abfallappcux", ["Kreis Cuxhaven"]),
        ("de.k4systems.abfallslk", ["Salzlandkreis"]),
        ("de.k4systems.abfallappzak", ["ZAK Kempten"]),
        ("de.zawsr", ["ZAW-SR"]),
        ("de.k4systems.teamorange", ["Kreis Würzburg"]),
        ("de.k4systems.abfallappvivo", ["Kreis Miesbach"]),
        ("de.k4systems.lkgr", ["Landkreis Görlitz"]),
        ("de.k4systems.zawdw", ["AWG Donau-Wald"]),
        ("de.k4systems.abfallappgib", ["Kreis Wesermarsch"]),
        ("de.k4systems.wuerzburg", ["Würzburg"]),
        ("de.k4systems.abfallappgap", ["Kreis Garmisch-Partenkirchen"]),
        ("de.k4systems.bonnorange", ["Bonn"]),
        ("de.gimik.apps.muellwecker_neuwied", ["Kreis Neuwied"]),
        ("abfallH.ucom.de", ["Kreis Heilbronn"]),
        ("de.k4systems.abfallappts", ["Kreis Traunstein"]),
        ("de.k4systems.awa", ["Augsburg"]),
        ("de.k4systems.abfallappfuerth", ["Kreis Fürth"]),
        ("de.k4systems.abfallwelt", ["Kreis Kitzingen"]),
        ("de.k4systems.lkemmendingen", ["Kreis Emmendingen"]),
        ("de.k4systems.abfallkreisrt", ["Kreis Reutlingen"]),
        ("de.abfallplus.tbrapp", ["Reutlingen"]),
        ("de.k4systems.abfallappmetz", ["Metzingen"]),
        ("de.k4systems.abfallappmyk", ["Kreis Mayen-Koblenz"]),
        ("de.k4systems.abfallappoal", ["Kreis Ostallgäu"]),
        ("de.k4systems.regioentsorgung", ["Alsdorf", "Baesweiler", "Eschweiler", "Heimbach", "Herzogenrath", "Inden", "Langerwehe", "Linnich", "Monschau", "Nideggen", "Niederzier", "Nörvenich", "Roetgen", "Simmerath", "Stolberg", "Vettweiß", "Würselen"]),
        ("de.k4systems.abfalllkbt", ["Kreis Bayreuth"]),
        ("de.k4systems.awvapp", ["Kreis Vechta"]),
        ("de.k4systems.aevapp", ["Schwarze Elster"]),
        ("de.k4systems.awbgp", ["Kreis Göppingen"]),
        ("de.k4systems.abfallhr", ["ALF Lahn-Fulda"]),
        ("de.k4systems.abfallappbh", ["Kreis Breisgau-Hochschwarzwald"]),
        ("de.k4systems.awgbassum", ["Kreis Diepholz"]),
        ("de.data_at_work.aws", ["Kreis Schaumburg"]),
        ("de.k4systems.hebhagen", ["Hagen"]),
        ("de.k4systems.meinawblm", ["Kreis Limburg-Weilburg"]),
        ("de.k4systems.abfallmsp", ["Landkreis Main-Spessart"]),
        ("de.k4systems.asoapp", ["Kreis Osterholz"]),
        ("de.k4systems.awistasta", ["Kreis Starnberg"]),
        ("de.ucom.abfallebe", ["Essen"]),
        ("de.k4systems.bawnapp", ["Kreis Nienburg / Weser"]),
        ("de.k4systems.abfallappol", ["Oldenburg"]),
        ("de.k4systems.awbrastatt", ["Kreis Rastatt"]),
        ("de.k4systems.abfallappmil", ["Kreis Miltenberg"]),
        ("de.k4systems.abfallsbk", ["Schwarzwald-Baar-Kreis"]),
        ("de.k4systems.wabapp", ["Westerwaldkreis"]),
        ("de.k4systems.llabfallapp", ["Kreis Landsberg am Lech"]),
        ("de.k4systems.lkruelzen", ["Kreis Uelzen"]),
        ("de.k4systems.abfallzak", ["Zollernalbkreis"]),
        ("de.k4systems.abfallappno", ["Neckar-Odenwald-Kreis"]),
        ("de.k4systems.udb", ["Burgenland (Landkreis)"]),
        ("de.k4systems.abfallappsig", ["Kreis Sigmaringen"]),
        ("de.k4systems.asf", ["Freiburg im Breisgau"]),
        ("de.drekopf.abfallplaner", ["Drekopf"]),
        ("de.k4systems.unterallgaeu", ["Rottweil", "Tuttlingen", "Waldshut", "Frankfurt (Oder)", "Prignitz"]),
        ("de.k4systems.landshutlk", ["Kreis Landshut"]),
        ("de.k4systems.zakb", ["Kreis Bergstraße"]),
        ("de.k4systems.awrplus", ["Kreis Rotenburg (Wümme)"]),
        ("de.k4systems.lkmabfallplus", ["München Landkreis"]),
        ("de.k4systems.athosmobil", ["ATHOS GmbH"]),
        ("de.k4systems.willkommen", ["Rottweil", "Tuttlingen", "Waldshut", "Frankfurt (Oder)", "Prignitz"]),
        ("de.idcontor.abfalllu", ["Ludwigshafen"]),
        ("de.ahrweiler.meinawb", ["Kreis Ahrweiler"]),
        ("de.edg.abfallapp", ["Entsorgung Dortmund GmbH (EDG)"]),
        ("de.biberach.abfallapp", ["Kreis Biberach"]),
        ("de.abfallplus.abfallappver", ["Kreis Verden"]),
        ("de.abfallplus.abfallappwt", ["Kreis Waldshut"]),
        ("de.remondis.rheinland", ["Remondis Rheinland"]),
        ("de.abfallplus.gfaabfallinfo", ["Kreis Lüneburg"]),
        ("de.abfallplus.abfalllkrw", ["Kreis Rottweil"]),
        ("de.cmcitymedia.shawaste", ["Kreis Schwäbisch-Hall"]),
    ]

    static let userAgentName: [String: String] = [
        "abfallH.ucom.de": "Landkreis HN",
        "abfallMA.ucom.de": "Abfall-Ma",
        "de.ahrweiler.meinawb": "Abfall App",
        "de.abfallwecker": "ABFALL+",
        "de.abfallplus.ahe": "AHE",
        "de.albagroup.app": "Abfuhrtermine",
        "de.biberach.abfallapp": "Abfall App",
        "de.cmcitymedia.hokwaste": "Abfallinfo HOK",
        "de.data_at_work.aws": "aws Schaumburg",
        "de.drekopf.abfallplaner": "Abfallplaner",
        "de.edg.abfallapp": "Abfall App",
        "de.gimik.apps.muellwecker_neuwied": "Müllwecker",
        "de.idcontor.abfalllu": "Abfall LU",
        "de.idcontor.abfallwbd": "WBD App",
        "de.k4systems.abfallappart": "ART App",
        "de.k4systems.abfallappbb": "Abfall-App",
        "de.k4systems.abfallappbh": "Abfall App",
        "de.k4systems.abfallappbk": "AbfallApp BK",
        "de.k4systems.abfallappclp": "Abfall App CLP",
        "de.k4systems.abfallappcux": "Abfall LK Cux",
        "de.k4systems.abfallappes": "Abfall-App",
        "de.k4systems.abfallappfds": "Abfall App FDS",
        "de.k4systems.abfallappfuerth": "Abfall-App",
        "de.k4systems.abfallappgap": "Abfall App",
        "de.k4systems.abfallappgib": "Abfall App",
        "de.k4systems.abfallappik": "AbfallApp IK",
        "de.k4systems.abfallappka": "Abfall App KA",
        "de.k4systems.abfallappla": "Abfall App",
        "de.k4systems.abfallapploe": "Abfall-App",
        "de.k4systems.abfallappmetz": "Abfall App",
        "de.k4systems.abfallappmil": "AbfallApp MIL",
        "de.k4systems.abfallappmol": "AbfallApp MOL",
        "de.k4systems.abfallappmyk": "AbfallApp Myk",
        "de.k4systems.abfallappnf": "Abfall-AppNF",
        "de.k4systems.abfallappno": "Abfall-App",
        "de.k4systems.abfallappoal": "Ostallgäu",
        "de.k4systems.abfallappog": "Ortenaukreis",
        "de.k4systems.abfallappol": "Abfall App OL",
        "de.k4systems.abfallapp": "AbfallApp",
        "de.k4systems.abfallapprv": "Abfall App RV",
        "de.k4systems.abfallappsig": "AbfallSIG",
        "de.k4systems.abfallappts": "AbfallApp TS",
        "de.k4systems.abfallappvivo": "Abfall App",
        "de.k4systems.abfallappvorue": "Abfall App",
        "de.k4systems.abfallappwug": "AbfallApp WUG",
        "de.k4systems.abfallappzak": "Abfall App",
        "de.k4systems.abfallhr": "Abfall HR",
        "de.k4systems.abfallinfoapp": "Abfallinfoapp",
        "de.k4systems.abfallinfocw": "AbfallinfoCW",
        "de.k4systems.abfallkreisrt": "AbfallKreisRT",
        "de.k4systems.abfalllkbt": "Abfall LK BT",
        "de.k4systems.abfalllkbz": "Abfall LK BZ",
        "de.k4systems.abfalllkswp": "Abfall LKSWP",
        "de.k4systems.abfallmsp": "Abfall MSP",
        "de.k4systems.abfallsbk": "Abfall SBK",
        "de.k4systems.abfallscout": "Abfall-Scout",
        "de.k4systems.abfallslk": "Abfall SLK",
        "de.k4systems.abfallwelt": "abfallwelt",
        "de.k4systems.abfallzak": "Abfall ZAK",
        "de.k4systems.aevapp": "AEV-App",
        "de.k4systems.asf": "ASF",
        "de.k4systems.asoapp": "ASO-App",
        "de.k4systems.athosmobil": "ATHOS mobil",
        "de.k4systems.avea": "AVEA-App",
        "de.k4systems.avlserviceplus": "AVL Service+",
        "de.k4systems.awa": "Abfallplaner",
        "de.k4systems.awbemsland": "AWB Emsland",
        "de.k4systems.awbgp": "AWB-GP",
        "de.k4systems.awbrastatt": "AWB Rastatt",
        "de.k4systems.awgbassum": "AWG Bassum",
        "de.k4systems.awistasta": "Awista-STA",
        "de.k4systems.awrplus": "AWR+",
        "de.k4systems.awvapp": "AWV App",
        "de.k4systems.bawnapp": "BAWNapp",
        "de.k4systems.bonnorange": "Abfallplaner",
        "de.k4systems.egst": "EGST",
        "de.k4systems.hebhagen": "HEB Hagen",
        "de.k4systems.kufiapp": "KUFI App",
        "de.k4systems.landshutlk": "Abfall App",
        "de.k4systems.leipziglk": "LK Leipzig",
        "de.k4systems.lkemmendingen": "LK Emmendingen",
        "de.k4systems.lkgoettingen": "LK Göttingen",
        "de.k4systems.lkgr": "LK GR",
        "de.k4systems.lkruelzen": "Abfall App",
        "de.k4systems.lkmabfallplus": "Abfall App",
        "de.k4systems.llabfallapp": "LL Abfall App",
        "de.k4systems.meinawblm": "Mein AWB LM",
        "de.k4systems.muellalarm": "MüllALARM",
        "de.k4systems.neustadtaisch": "Abfall-App",
        "de.k4systems.regioentsorgung": "RE-entsorgt",
        "de.k4systems.teamorange": "team orange",
        "de.k4systems.udb": "Müllabfuhr",
        "de.k4systems.unterallgaeu": "Unterallgäu",
        "de.k4systems.wabapp": "WAB-App",
        "de.k4systems.willkommen": "Will Kommen",
        "de.k4systems.wuerzburg": "Stadtreiniger",
        "de.k4systems.zakb": "zakb",
        "de.k4systems.zawdw": "ZAW DW",
        "de.ucom.abfallavr": "AVR Abfall",
        "de.ucom.abfallebe": "Wir räumen ab!",
        "de.zawsr": "ZAW-SR",
    ]
}
